// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBWizardWebAPIDay18Lab.Models;

public partial class Employee
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Job { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? Salary { get; set; }

    public byte[] Photo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? HireDate { get; set; }

    [StringLength(50)]
    public string ReportTo { get; set; }

    public bool IsDeleted { get; set; }
}